insert into Customer ( Name, address) values ('Dorri', '0024 East Parkway');
insert into Customer ( Name, address) values ('Gena', '35 Mcbride Drive');
insert into Customer ( Name, address) values ('Elbertine', '021 Bobwhite Point');
insert into Customer ( Name, address) values ('Ajay', '777 Colorado Avenue');
insert into Customer ( Name, address) values ('Allyn', '3 Sutherland Pass');
insert into Customer ( Name, address) values ('Leopold', '84132 Elmside Crossing');
insert into Customer ( Name, address) values ('Anetta', '261 Fuller Trail');
insert into Customer ( Name, address) values ('Beniamino', '943 Village Green Road');
insert into Customer ( Name, address) values ('Bryana', '657 Golf Course Lane');
insert into Customer ( Name, address) values ( 'Valentina', '697 Village Way');
insert into Customer ( Name, address) values ( 'Berkie', '5 Calypso Point');
insert into Customer ( Name, address) values ( 'Duke', '423 Shasta Pass');
insert into Customer ( Name, address) values ( 'Axe', '095 Mendota Street');
insert into Customer ( Name, address) values ( 'Zitella', '7 Knutson Avenue');
insert into Customer ( Name, address) values ( 'Larisa', '3 Luster Court');
insert into Customer ( Name, address) values ( 'Gustie', '7991 Hovde Drive');
insert into Customer ( Name, address) values ( 'Pearline', '183 Mallory Place');
insert into Customer ( Name, address) values ( 'Eleonora', '97040 Kennedy Way');
insert into Customer ( Name, address) values ( 'Gerrilee', '906 Bunting Road');
insert into Customer ( Name, address) values ( 'Frasco', '67 Oxford Crossing');
insert into Customer ( Name, address) values ( 'Cyrill', '4 Mariners Cove Junction');
insert into Customer ( Name, address) values ( 'Iolande', '07018 Fair Oaks Hill');
insert into Customer ( Name, address) values ( 'Lynett', '20 5th Drive');
insert into Customer ( Name, address) values ( 'Annalee', '69295 Fallview Court');
insert into Customer ( Name, address) values ( 'Banky', '1770 John Wall Alley');
insert into Customer ( Name, address) values ( 'Phillida', '3648 Merchant Parkway');
insert into Customer ( Name, address) values ( 'Tomkin', '404 Lyons Court');
insert into Customer ( Name, address) values ( 'Gae', '1 Spohn Alley');
insert into Customer ( Name, address) values ( 'Merrielle', '83908 Havey Way');
insert into Customer ( Name, address) values ( 'Diannne', '564 Comanche Plaza');
insert into Customer ( Name, address) values ( 'Cesaro', '19097 Nova Crossing');
insert into Customer ( Name, address) values ( 'Kial', '48 Ilene Court');
insert into Customer ( Name, address) values ( 'Kaleb', '467 Glacier Hill Way');
insert into Customer ( Name, address) values ( 'Roldan', '1 Eggendart Park');
insert into Customer ( Name, address) values ( 'Jaquenetta', '95994 Barby Junction');
insert into Customer ( Name, address) values ( 'Nicolette', '267 Everett Terrace');
insert into Customer ( Name, address) values ( 'Haleigh', '0287 Fuller Way');
insert into Customer ( Name, address) values ( 'Kain', '1529 Arizona Avenue');
insert into Customer ( Name, address) values ( 'Dominick', '494 Warrior Place');
insert into Customer ( Name, address) values ( 'Dyane', '0295 Jenifer Terrace');
insert into Customer ( Name, address) values ( 'Abbie', '652 Wayridge Way');
insert into Customer ( Name, address) values ( 'Cecilla', '1 Sachs Pass');
insert into Customer ( Name, address) values ( 'Patten', '02558 Parkside Pass');
insert into Customer ( Name, address) values ( 'Arch', '2 Sugar Lane');
insert into Customer ( Name, address) values ( 'Cesya', '59 Southridge Hill');
insert into Customer ( Name, address) values ( 'Bronson', '9 1st Terrace');
insert into Customer ( Name, address) values ( 'Kurt', '4281 Bunting Place');
insert into Customer ( Name, address) values ( 'Lorne', '3204 Cherokee Center');
insert into Customer ( Name, address) values ( 'Tammara', '7 Clyde Gallagher Center');
insert into Customer ( Name, address) values ( 'Jerrie', '00 Dennis Avenue');
insert into Customer ( Name, address) values ( 'Alexi', '6448 Graceland Crossing');
insert into Customer ( Name, address) values ( 'Lazarus', '48 Dwight Lane');
insert into Customer ( Name, address) values ( 'Kriste', '6635 Alpine Road');
insert into Customer ( Name, address) values ( 'Carr', '0616 Ramsey Circle');
insert into Customer ( Name, address) values ( 'Evin', '179 Washington Junction');
insert into Customer ( Name, address) values ( 'Hinda', '3607 Crowley Plaza');
insert into Customer ( Name, address) values ( 'Merell', '07 Eagan Circle');
insert into Customer ( Name, address) values ( 'Bail', '01 Shasta Avenue');
insert into Customer ( Name, address) values ( 'Lanni', '76240 Holy Cross Crossing');
insert into Customer ( Name, address) values ( 'Ralf', '7862 Golf Crossing');
insert into Customer ( Name, address) values ( 'Tedda', '95 Gateway Place');
insert into Customer ( Name, address) values ( 'Derrick', '266 Merrick Pass');
insert into Customer ( Name, address) values ( 'Leigh', '0214 Gale Pass');
insert into Customer ( Name, address) values ( 'Felizio', '28295 Gateway Lane');
insert into Customer ( Name, address) values ( 'Adey', '7 Kedzie Avenue');
insert into Customer ( Name, address) values ( 'Karole', '2383 Clemons Plaza');
insert into Customer ( Name, address) values ( 'Kelila', '28 Westport Circle');
insert into Customer ( Name, address) values ( 'Augy', '953 Prairieview Park');
insert into Customer ( Name, address) values ( 'Dina', '518 La Follette Street');
insert into Customer ( Name, address) values ( 'Adriane', '90 Red Cloud Terrace');
insert into Customer ( Name, address) values ( 'Arvie', '78 Brown Park');
insert into Customer ( Name, address) values ( 'Burl', '4 Northview Road');
insert into Customer ( Name, address) values ( 'Vickie', '535 Kropf Trail');
insert into Customer ( Name, address) values ( 'Dyanne', '65911 Weeping Birch Park');
insert into Customer ( Name, address) values ( 'Andrew', '14 Evergreen Pass');
insert into Customer ( Name, address) values ( 'Gerrilee', '7337 Judy Lane');
insert into Customer ( Name, address) values ( 'Lolita', '43 Lawn Avenue');
insert into Customer ( Name, address) values ( 'Renie', '342 Fremont Crossing');
insert into Customer ( Name, address) values ( 'Anton', '4 Dapin Court');
insert into Customer ( Name, address) values ( 'Edith', '9 Valley Edge Drive');
insert into Customer ( Name, address) values ( 'Glenda', '117 Lakeland Circle');
insert into Customer ( Name, address) values ( 'Tabor', '154 Waxwing Street');
insert into Customer ( Name, address) values ( 'Charmion', '999 Rockefeller Crossing');
insert into Customer ( Name, address) values ( 'Clive', '42 Northridge Lane');
insert into Customer ( Name, address) values ( 'Vic', '6958 Redwing Drive');
insert into Customer ( Name, address) values ( 'Cate', '194 Westport Junction');
insert into Customer ( Name, address) values ( 'Gray', '3 Ridge Oak Terrace');
insert into Customer ( Name, address) values ( 'Celina', '5 Atwood Pass');
insert into Customer ( Name, address) values ( 'Gerardo', '80 Dunning Place');
insert into Customer ( Name, address) values ( 'Krystle', '9246 Raven Hill');
insert into Customer ( Name, address) values ( 'Ev', '48 Lillian Road');
insert into Customer ( Name, address) values ( 'Madel', '1716 Myrtle Drive');
insert into Customer ( Name, address) values ( 'Danit', '58605 Artisan Place');
insert into Customer ( Name, address) values ( 'Patrice', '6350 Knutson Plaza');
insert into Customer ( Name, address) values ( 'Moss', '40642 Del Mar Trail');
insert into Customer ( Name, address) values ( 'Gilly', '1584 Del Mar Street');
insert into Customer ( Name, address) values ( 'Jesus', '90 Fairfield Avenue');
insert into Customer ( Name, address) values ( 'Mitzi', '96 Old Shore Parkway');
insert into Customer ( Name, address) values ( 'Renard', '85 Debs Center');
insert into Customer ( Name, address) values ( 'Zita', '2 Eastwood Drive');


insert into Product ( name, price, quantity) values ('Longtom Filmy Fern', ' 17.35', 39);
insert into Product ( name, price, quantity) values ('Water Arum', ' 8.05', 37);
insert into Product ( name, price, quantity) values ('Hall''s Columbiadoria', ' 17.20', 30);
insert into Product ( name, price, quantity) values ('Pinkscale Blazing Star', ' 26.85', 60);
insert into Product ( name, price, quantity) values ('Longhair Sedge', ' 21.00', 38);
insert into Product ( name, price, quantity) values ('Undulate Jelly Lichen', ' 7.15', 51);
insert into Product ( name, price, quantity) values ('Arctic Seashore Willow', ' 23.05', 4);
insert into Product ( name, price, quantity) values ('Sageleaf Willow', ' 25.60', 46);
insert into Product ( name, price, quantity) values ('Common Gum Cistus', ' 22.28', 27);
insert into Product ( name, price, quantity) values ( 'Smooth Joyweed', ' 0.22', 32);
insert into Product ( name, price, quantity) values ( 'Ontario Goldenrod', ' 25.09', 51);
insert into Product ( name, price, quantity) values ( 'Velvet Lupine', ' 2.72', 53);
insert into Product ( name, price, quantity) values ( 'Fabronia Moss', ' 8.54', 21);
insert into Product ( name, price, quantity) values ( 'Cream Milkvetch', ' 21.79', 21);
insert into Product ( name, price, quantity) values ( 'Douglas'' Clover', ' 29.75', 30);
insert into Product ( name, price, quantity) values ( 'Yarrow', ' 25.99', 44);
insert into Product ( name, price, quantity) values ( 'Pasqueflower', ' 0.67', 4);
insert into Product ( name, price, quantity) values ( 'Spike Lichen', ' 19.79', 5);
insert into Product ( name, price, quantity) values ( 'Lemhi Milkvetch', ' 0.38', 31);
insert into Product ( name, price, quantity) values ( 'Hibiscus', ' 19.91', 39);
insert into Product ( name, price, quantity) values ( 'Crandall''s Beardtongue', ' 20.98', 13);
insert into Product ( name, price, quantity) values ( 'Spleenwort', ' 3.20', 31);
insert into Product ( name, price, quantity) values ( 'Yukon Pine', ' 12.48', 34);
insert into Product ( name, price, quantity) values ( 'Pollock''s Mill Blackberry', ' 8.58', 2);
insert into Product ( name, price, quantity) values ( 'Arctic Pearlwort', ' 12.04', 29);
insert into Product ( name, price, quantity) values ( 'Hybrid Ladyslipper', ' 20.70', 59);
insert into Product ( name, price, quantity) values ( 'Dicranum Moss', ' 16.50', 2);
insert into Product ( name, price, quantity) values ( 'Texas Craglily', ' 20.07', 39);
insert into Product ( name, price, quantity) values ( 'Higgins'' Beardtongue', ' 23.44', 23);
insert into Product ( name, price, quantity) values ( 'Allegheny Monkeyflower', ' 1.83', 53);
insert into Product ( name, price, quantity) values ( 'California Brodiaea', ' 0.46', 48);
insert into Product ( name, price, quantity) values ( 'Fringed Willowherb', ' 8.37', 55);
insert into Product ( name, price, quantity) values ( 'Mountain Monardella', ' 29.02', 9);
insert into Product ( name, price, quantity) values ( 'Western Buttercup', ' 22.81', 15);
insert into Product ( name, price, quantity) values ( 'Aladdin''s Slippers', ' 7.77', 11);
insert into Product ( name, price, quantity) values ( 'Swamp Morning-glory', ' 3.75', 58);
insert into Product ( name, price, quantity) values ( 'Annual Marsh Elder', ' 17.57', 4);
insert into Product ( name, price, quantity) values ( 'Front Range Milkvetch', ' 26.89', 21);
insert into Product ( name, price, quantity) values ( 'Plummer''s Mariposa Lily', ' 4.98', 60);
insert into Product ( name, price, quantity) values ( 'Japanese Plum', ' 11.67', 41);
insert into Product ( name, price, quantity) values ( 'Hairy New York Aster', ' 27.94', 4);
insert into Product ( name, price, quantity) values ( 'Oriental Wheat', ' 26.48', 31);
insert into Product ( name, price, quantity) values ( 'Switchgrass', ' 14.05', 24);
insert into Product ( name, price, quantity) values ( 'Bridgotree', ' 2.12', 11);
insert into Product ( name, price, quantity) values ( 'Succisa', ' 5.73', 2);
insert into Product ( name, price, quantity) values ( 'Desertmountain Blue Eyed Mary', ' 24.20', 52);
insert into Product ( name, price, quantity) values ( 'Mauka', ' 15.87', 18);
insert into Product ( name, price, quantity) values ( 'Small Beggarticks', ' 4.73', 29);
insert into Product ( name, price, quantity) values ( 'Trailing Abutilon', ' 13.48', 37);
insert into Product ( name, price, quantity) values ( 'Yelloweyes', ' 10.80', 57);
insert into Product ( name, price, quantity) values ( 'Lecidea Lichen', ' 19.56', 12);
insert into Product ( name, price, quantity) values ( 'Bill Williams Mountain Giant Hyssop', ' 26.37', 37);
insert into Product ( name, price, quantity) values ( 'Elongate Pohlia Moss', ' 22.37', 58);
insert into Product ( name, price, quantity) values ( 'Parish''s Phacelia', ' 17.16', 54);
insert into Product ( name, price, quantity) values ( 'Longbeard Mariposa Lily', ' 3.53', 4);
insert into Product ( name, price, quantity) values ( 'Wavyleaf Silktassel', ' 19.86', 55);
insert into Product ( name, price, quantity) values ( 'Chilean Gunnera', ' 17.62', 15);
insert into Product ( name, price, quantity) values ( 'Violet', ' 19.89', 17);
insert into Product ( name, price, quantity) values ( 'Sandplain False Foxglove', ' 23.85', 6);
insert into Product ( name, price, quantity) values ( 'Forest Peperomia', ' 6.65', 58);
insert into Product ( name, price, quantity) values ( 'Sierra Beardtongue', ' 19.23', 20);
insert into Product ( name, price, quantity) values ( 'Honeywort', ' 1.61', 30);
insert into Product ( name, price, quantity) values ( 'Rosette Lichen', ' 8.92', 1);
insert into Product ( name, price, quantity) values ( 'Pale Lobelia', ' 14.42', 45);
insert into Product ( name, price, quantity) values ( 'Dwarf Iliau', ' 12.92', 18);
insert into Product ( name, price, quantity) values ( 'San Diego Sedge', ' 16.87', 57);
insert into Product ( name, price, quantity) values ( 'California Fescue', ' 8.82', 6);
insert into Product ( name, price, quantity) values ( 'Fleshy Clapdaisy', ' 9.95', 4);
insert into Product ( name, price, quantity) values ( 'Paraguayan Purslane', ' 22.28', 39);
insert into Product ( name, price, quantity) values ( 'Raggedlip Orchid', ' 1.99', 15);
insert into Product ( name, price, quantity) values ( 'Small Matweed', ' 1.48', 52);
insert into Product ( name, price, quantity) values ( 'Cudrania', ' 15.93', 2);
insert into Product ( name, price, quantity) values ( 'New Mexico Beeblossom', ' 4.88', 19);
insert into Product ( name, price, quantity) values ( 'Doublehorn Calicoflower', ' 7.17', 46);
insert into Product ( name, price, quantity) values ( 'Smooth Brome', ' 10.04', 41);

insert into "Order" (CustomerId, ProductId, Quantity, OrderDate) values (60, 23, 2, '11/13/2022');
insert into "Order" (CustomerId, ProductId, Quantity, OrderDate) values (7, 34, 10, '4/1/2022');
insert into "Order" (CustomerId, ProductId, Quantity, OrderDate) values (79, 28, 11, '6/2/2022');
insert into "Order" (CustomerId, ProductId, Quantity, OrderDate) values (85, 24, 12, '6/25/2022');
insert into "Order" (CustomerId, ProductId, Quantity, OrderDate) values (22, 33, 3, '1/21/2023');
insert into "Order" (CustomerId, ProductId, Quantity, OrderDate) values (1, 69, 2, '3/13/2023');
insert into "Order" (CustomerId, ProductId, Quantity, OrderDate) values (64, 56, 11, '8/21/2022');
insert into "Order" (CustomerId, ProductId, Quantity, OrderDate) values (26, 60, 3, '6/18/2022');
insert into "Order" (CustomerId, ProductId, Quantity, OrderDate) values (36, 40, 3, '6/21/2022');
insert into "Order" (CustomerId, ProductId, Quantity, OrderDate) values (73, 75, 1, '11/30/2022');
insert into "Order" (CustomerId, ProductId, Quantity, OrderDate) values (18, 15, 7, '10/12/2022');
insert into "Order" (CustomerId, ProductId, Quantity, OrderDate) values (52, 40, 3, '2/15/2023');
insert into "Order" (CustomerId, ProductId, Quantity, OrderDate) values (60, 42, 5, '5/23/2022');
insert into "Order" (CustomerId, ProductId, Quantity, OrderDate) values (89, 32, 3, '11/16/2022');
insert into "Order" (CustomerId, ProductId, Quantity, OrderDate) values (66, 59, 4, '3/15/2022');
insert into "Order" (CustomerId, ProductId, Quantity, OrderDate) values (64, 20, 3, '7/23/2022');
insert into "Order" (CustomerId, ProductId, Quantity, OrderDate) values (47, 23, 1, '1/7/2023');
insert into "Order" (CustomerId, ProductId, Quantity, OrderDate) values (85, 20, 10, '10/30/2022');
insert into "Order" (CustomerId, ProductId, Quantity, OrderDate) values (87, 30, 12, '1/29/2023');
insert into "Order" (CustomerId, ProductId, Quantity, OrderDate) values (83, 59, 1, '9/12/2022');
insert into "Order" (CustomerId, ProductId, Quantity, OrderDate) values (90, 6, 1, '4/16/2022');
insert into "Order" (CustomerId, ProductId, Quantity, OrderDate) values (22, 45, 9, '10/22/2022');
insert into "Order" (CustomerId, ProductId, Quantity, OrderDate) values (76, 53, 9, '1/22/2023');
insert into "Order" (CustomerId, ProductId, Quantity, OrderDate) values (18, 15, 5, '5/22/2022');
insert into "Order" (CustomerId, ProductId, Quantity, OrderDate) values (65, 13, 7, '8/19/2022');
insert into "Order" (CustomerId, ProductId, Quantity, OrderDate) values (82, 59, 10, '8/24/2022');
insert into "Order" (CustomerId, ProductId, Quantity, OrderDate) values (2, 48, 9, '8/1/2022');
insert into "Order" (CustomerId, ProductId, Quantity, OrderDate) values (87, 67, 7, '5/26/2022');
insert into "Order" (CustomerId, ProductId, Quantity, OrderDate) values (87, 64, 8, '3/17/2022');
insert into "Order" (CustomerId, ProductId, Quantity, OrderDate) values (76, 54, 2, '2/28/2023');
insert into "Order" (CustomerId, ProductId, Quantity, OrderDate) values (82, 54, 7, '6/13/2022');
insert into "Order" (CustomerId, ProductId, Quantity, OrderDate) values (13, 54, 11, '1/17/2023');
insert into "Order" (CustomerId, ProductId, Quantity, OrderDate) values (66, 3, 3, '7/24/2022');
insert into "Order" (CustomerId, ProductId, Quantity, OrderDate) values (89, 16, 9, '2/15/2023');
insert into "Order" (CustomerId, ProductId, Quantity, OrderDate) values (24, 59, 2, '6/21/2022');
insert into "Order" (CustomerId, ProductId, Quantity, OrderDate) values (65, 21, 5, '6/12/2022');
insert into "Order" (CustomerId, ProductId, Quantity, OrderDate) values (82, 71, 11, '8/9/2022');
insert into "Order" (CustomerId, ProductId, Quantity, OrderDate) values (64, 38, 11, '9/21/2022');
insert into "Order" (CustomerId, ProductId, Quantity, OrderDate) values (19, 25, 11, '8/24/2022');
insert into "Order" (CustomerId, ProductId, Quantity, OrderDate) values (91, 67, 7, '3/19/2022');
insert into "Order" (CustomerId, ProductId, Quantity, OrderDate) values (5, 3, 2, '2/28/2023');
insert into "Order" (CustomerId, ProductId, Quantity, OrderDate) values (88, 75, 11, '1/4/2023');
insert into "Order" (CustomerId, ProductId, Quantity, OrderDate) values (43, 44, 6, '10/14/2022');
insert into "Order" (CustomerId, ProductId, Quantity, OrderDate) values (81, 62, 7, '9/9/2022');
insert into "Order" (CustomerId, ProductId, Quantity, OrderDate) values (52, 16, 11, '2/6/2023');
insert into "Order" (CustomerId, ProductId, Quantity, OrderDate) values (59, 68, 7, '3/31/2022');
insert into "Order" (CustomerId, ProductId, Quantity, OrderDate) values (35, 25, 12, '12/19/2022');
insert into "Order" (CustomerId, ProductId, Quantity, OrderDate) values (28, 61, 6, '3/30/2022');
insert into "Order" (CustomerId, ProductId, Quantity, OrderDate) values (41, 39, 11, '12/11/2022');
insert into "Order" (CustomerId, ProductId, Quantity, OrderDate) values (36, 2, 11, '6/4/2022');
insert into "Order" (CustomerId, ProductId, Quantity, OrderDate) values (68, 38, 7, '7/26/2022');
insert into "Order" (CustomerId, ProductId, Quantity, OrderDate) values (40, 3, 8, '1/17/2023');
insert into "Order" (CustomerId, ProductId, Quantity, OrderDate) values (70, 25, 11, '2/14/2023');
insert into "Order" (CustomerId, ProductId, Quantity, OrderDate) values (99, 62, 3, '5/8/2022');
insert into "Order" (CustomerId, ProductId, Quantity, OrderDate) values (64, 61, 7, '7/22/2022');
insert into "Order" (CustomerId, ProductId, Quantity, OrderDate) values (28, 13, 1, '4/1/2022');
insert into "Order" (CustomerId, ProductId, Quantity, OrderDate) values (82, 26, 11, '6/17/2022');
insert into "Order" (CustomerId, ProductId, Quantity, OrderDate) values (96, 69, 10, '1/4/2023');
insert into "Order" (CustomerId, ProductId, Quantity, OrderDate) values (24, 60, 11, '11/14/2022');
insert into "Order" (CustomerId, ProductId, Quantity, OrderDate) values (9, 54, 11, '12/23/2022');
insert into "Order" (CustomerId, ProductId, Quantity, OrderDate) values (9, 63, 2, '1/14/2023');
insert into "Order" (CustomerId, ProductId, Quantity, OrderDate) values (48, 23, 3, '9/15/2022');
insert into "Order" (CustomerId, ProductId, Quantity, OrderDate) values (49, 6, 1, '2/7/2023');
insert into "Order" (CustomerId, ProductId, Quantity, OrderDate) values (68, 36, 12, '1/25/2023');
insert into "Order" (CustomerId, ProductId, Quantity, OrderDate) values (76, 25, 11, '8/4/2022');
insert into "Order" (CustomerId, ProductId, Quantity, OrderDate) values (96, 13, 7, '8/16/2022');
insert into "Order" (CustomerId, ProductId, Quantity, OrderDate) values (42, 73, 5, '4/30/2022');
insert into "Order" (CustomerId, ProductId, Quantity, OrderDate) values (27, 49, 5, '8/11/2022');
insert into "Order" (CustomerId, ProductId, Quantity, OrderDate) values (76, 12, 5, '10/8/2022');
insert into "Order" (CustomerId, ProductId, Quantity, OrderDate) values (82, 16, 3, '7/29/2022');
insert into "Order" (CustomerId, ProductId, Quantity, OrderDate) values (94, 70, 6, '1/18/2023');
insert into "Order" (CustomerId, ProductId, Quantity, OrderDate) values (93, 37, 5, '1/21/2023');
insert into "Order" (CustomerId, ProductId, Quantity, OrderDate) values (34, 54, 4, '7/22/2022');
insert into "Order" (CustomerId, ProductId, Quantity, OrderDate) values (49, 21, 4, '5/3/2022');
insert into "Order" (CustomerId, ProductId, Quantity, OrderDate) values (21, 16, 3, '5/20/2022');
insert into "Order" (CustomerId, ProductId, Quantity, OrderDate) values (35, 56, 1, '12/16/2022');
insert into "Order" (CustomerId, ProductId, Quantity, OrderDate) values (93, 59, 3, '8/22/2022');
insert into "Order" (CustomerId, ProductId, Quantity, OrderDate) values (9, 28, 9, '4/21/2022');
insert into "Order" (CustomerId, ProductId, Quantity, OrderDate) values (3, 39, 8, '12/7/2022');
insert into "Order" (CustomerId, ProductId, Quantity, OrderDate) values (67, 48, 8, '5/26/2022');
insert into "Order" (CustomerId, ProductId, Quantity, OrderDate) values (40, 32, 7, '5/23/2022');
insert into "Order" (CustomerId, ProductId, Quantity, OrderDate) values (6, 36, 12, '10/19/2022');
insert into "Order" (CustomerId, ProductId, Quantity, OrderDate) values (36, 55, 6, '10/31/2022');
insert into "Order" (CustomerId, ProductId, Quantity, OrderDate) values (10, 68, 4, '4/23/2022');
insert into "Order" (CustomerId, ProductId, Quantity, OrderDate) values (80, 44, 7, '2/9/2023');
insert into "Order" (CustomerId, ProductId, Quantity, OrderDate) values (1, 75, 8, '11/14/2022');
insert into "Order" (CustomerId, ProductId, Quantity, OrderDate) values (18, 37, 12, '6/7/2022');
insert into "Order" (CustomerId, ProductId, Quantity, OrderDate) values (84, 39, 3, '11/6/2022');
insert into "Order" (CustomerId, ProductId, Quantity, OrderDate) values (27, 51, 10, '7/2/2022');
insert into "Order" (CustomerId, ProductId, Quantity, OrderDate) values (21, 75, 3, '5/12/2022');
insert into "Order" (CustomerId, ProductId, Quantity, OrderDate) values (65, 65, 12, '11/6/2022');
insert into "Order" (CustomerId, ProductId, Quantity, OrderDate) values (74, 70, 3, '10/5/2022');
insert into "Order" (CustomerId, ProductId, Quantity, OrderDate) values (71, 64, 2, '1/13/2023');
insert into "Order" (CustomerId, ProductId, Quantity, OrderDate) values (43, 73, 12, '10/10/2022');
insert into "Order" (CustomerId, ProductId, Quantity, OrderDate) values (7, 12, 10, '5/18/2022');
insert into "Order" (CustomerId, ProductId, Quantity, OrderDate) values (50, 22, 2, '10/9/2022');
insert into "Order" (CustomerId, ProductId, Quantity, OrderDate) values (73, 50, 6, '7/24/2022');
insert into "Order" (CustomerId, ProductId, Quantity, OrderDate) values (41, 32, 8, '10/13/2022');
insert into "Order" (CustomerId, ProductId, Quantity, OrderDate) values (40, 15, 1, '2/3/2023');
insert into "Order" (CustomerId, ProductId, Quantity, OrderDate) values (2, 44, 8, '10/26/2022');
insert into "Order" (CustomerId, ProductId, Quantity, OrderDate) values (22, 27, 6, '6/19/2022');
insert into "Order" (CustomerId, ProductId, Quantity, OrderDate) values (75, 67, 5, '1/27/2023');
insert into "Order" (CustomerId, ProductId, Quantity, OrderDate) values (87, 2, 2, '4/30/2022');
insert into "Order" (CustomerId, ProductId, Quantity, OrderDate) values (43, 5, 6, '2/13/2023');
insert into "Order" (CustomerId, ProductId, Quantity, OrderDate) values (13, 29, 8, '1/31/2023');
insert into "Order" (CustomerId, ProductId, Quantity, OrderDate) values (83, 28, 11, '2/13/2023');
insert into "Order" (CustomerId, ProductId, Quantity, OrderDate) values (41, 18, 4, '11/11/2022');
insert into "Order" (CustomerId, ProductId, Quantity, OrderDate) values (40, 26, 5, '2/5/2023');
insert into "Order" (CustomerId, ProductId, Quantity, OrderDate) values (78, 10, 5, '6/23/2022');
insert into "Order" (CustomerId, ProductId, Quantity, OrderDate) values (35, 13, 3, '6/23/2022');
insert into "Order" (CustomerId, ProductId, Quantity, OrderDate) values (99, 54, 11, '1/15/2023');
insert into "Order" (CustomerId, ProductId, Quantity, OrderDate) values (91, 10, 12, '9/21/2022');
insert into "Order" (CustomerId, ProductId, Quantity, OrderDate) values (28, 46, 9, '5/12/2022');
insert into "Order" (CustomerId, ProductId, Quantity, OrderDate) values (60, 19, 4, '7/3/2022');
insert into "Order" (CustomerId, ProductId, Quantity, OrderDate) values (66, 58, 7, '4/29/2022');
insert into "Order" (CustomerId, ProductId, Quantity, OrderDate) values (68, 35, 11, '5/29/2022');
insert into "Order" (CustomerId, ProductId, Quantity, OrderDate) values (87, 55, 5, '9/24/2022');
insert into "Order" (CustomerId, ProductId, Quantity, OrderDate) values (41, 43, 12, '10/13/2022');
insert into "Order" (CustomerId, ProductId, Quantity, OrderDate) values (86, 56, 12, '10/8/2022');
insert into "Order" (CustomerId, ProductId, Quantity, OrderDate) values (57, 8, 8, '8/12/2022');
insert into "Order" (CustomerId, ProductId, Quantity, OrderDate) values (32, 54, 10, '10/10/2022');
insert into "Order" (CustomerId, ProductId, Quantity, OrderDate) values (56, 70, 3, '12/10/2022');
insert into "Order" (CustomerId, ProductId, Quantity, OrderDate) values (3, 51, 11, '11/7/2022');
insert into "Order" (CustomerId, ProductId, Quantity, OrderDate) values (98, 18, 10, '1/19/2023');
insert into "Order" (CustomerId, ProductId, Quantity, OrderDate) values (77, 47, 5, '4/21/2022');
insert into "Order" (CustomerId, ProductId, Quantity, OrderDate) values (59, 69, 1, '2/3/2023');
insert into "Order" (CustomerId, ProductId, Quantity, OrderDate) values (93, 4, 12, '1/26/2023');
insert into "Order" (CustomerId, ProductId, Quantity, OrderDate) values (63, 11, 9, '10/21/2022');
insert into "Order" (CustomerId, ProductId, Quantity, OrderDate) values (32, 15, 2, '2/1/2023');
insert into "Order" (CustomerId, ProductId, Quantity, OrderDate) values (20, 27, 6, '3/8/2023');
insert into "Order" (CustomerId, ProductId, Quantity, OrderDate) values (65, 71, 5, '10/8/2022');
insert into "Order" (CustomerId, ProductId, Quantity, OrderDate) values (2, 49, 5, '5/31/2022');
insert into "Order" (CustomerId, ProductId, Quantity, OrderDate) values (55, 47, 12, '2/2/2023');
insert into "Order" (CustomerId, ProductId, Quantity, OrderDate) values (96, 14, 10, '8/24/2022');
insert into "Order" (CustomerId, ProductId, Quantity, OrderDate) values (90, 70, 9, '2/3/2023');
insert into "Order" (CustomerId, ProductId, Quantity, OrderDate) values (74, 74, 1, '10/3/2022');
insert into "Order" (CustomerId, ProductId, Quantity, OrderDate) values (38, 63, 3, '4/7/2022');
insert into "Order" (CustomerId, ProductId, Quantity, OrderDate) values (61, 29, 9, '8/9/2022');
insert into "Order" (CustomerId, ProductId, Quantity, OrderDate) values (40, 56, 12, '2/11/2023');
insert into "Order" (CustomerId, ProductId, Quantity, OrderDate) values (85, 41, 1, '4/17/2022');
insert into "Order" (CustomerId, ProductId, Quantity, OrderDate) values (74, 15, 11, '8/5/2022');
insert into "Order" (CustomerId, ProductId, Quantity, OrderDate) values (21, 5, 1, '9/6/2022');
insert into "Order" (CustomerId, ProductId, Quantity, OrderDate) values (20, 38, 8, '3/13/2023');
insert into "Order" (CustomerId, ProductId, Quantity, OrderDate) values (17, 33, 3, '7/20/2022');
insert into "Order" (CustomerId, ProductId, Quantity, OrderDate) values (10, 4, 2, '12/5/2022');
insert into "Order" (CustomerId, ProductId, Quantity, OrderDate) values (37, 23, 1, '3/30/2022');
insert into "Order" (CustomerId, ProductId, Quantity, OrderDate) values (44, 63, 8, '8/31/2022');
insert into "Order" (CustomerId, ProductId, Quantity, OrderDate) values (34, 15, 10, '9/21/2022');
insert into "Order" (CustomerId, ProductId, Quantity, OrderDate) values (80, 31, 1, '5/12/2022');
insert into "Order" (CustomerId, ProductId, Quantity, OrderDate) values (90, 31, 1, '3/18/2022');
